// Demo movies data - Netflix style
export const DEMO_MOVIES = [
  {
    id: '1',
    title: 'El Último Horizonte',
    description: 'En un mundo post-apocalíptico, un grupo de supervivientes debe cruzar territorios peligrosos para encontrar una nueva casa. Una épica historia de supervivencia y esperanza.',
    thumbnail: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'accion',
    year: 2024,
    duration: 148,
    rating: 8.7,
    featured: true,
    language: 'Español'
  },
  {
    id: '2',
    title: 'Corazón de Fuego',
    description: 'Una apasionada historia de amor que transciende las barreras del tiempo. Dos almas destinadas a encontrarse en diferentes épocas.',
    thumbnail: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'romance',
    year: 2024,
    duration: 125,
    rating: 7.9,
    featured: false,
    language: 'Español'
  },
  {
    id: '3',
    title: 'Sombras del Pasado',
    description: 'Un thriller psicológico que te mantendrá al borde del asiento. Secretos oscuros emergen cuando una familia regresa a su antigua casa.',
    thumbnail: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'terror',
    year: 2023,
    duration: 118,
    rating: 8.2,
    featured: true,
    language: 'Español'
  },
  {
    id: '4',
    title: 'Misión Galaxia',
    description: 'La humanidad enfrenta su mayor desafío. Un equipo de astronautas debe salvar la Tierra de una amenaza interestelar.',
    thumbnail: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'ciencia-ficcion',
    year: 2024,
    duration: 156,
    rating: 9.1,
    featured: true,
    language: 'Español'
  },
  {
    id: '5',
    title: 'Risas Inesperadas',
    description: 'Una comedia irreverente sobre un grupo de amigos que se ven envueltos en situaciones delirantes durante un viaje por carretera.',
    thumbnail: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'comedia',
    year: 2024,
    duration: 112,
    rating: 7.5,
    featured: false,
    language: 'Español'
  },
  {
    id: '6',
    title: 'El Juramento',
    description: 'Un drama intenso sobre lealtad, traición y redención. Cuando la familia y el deber chocan, las consecuencias son devastadoras.',
    thumbnail: 'https://images.unsplash.com/photo-1533928298208-27ff66555d8d?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'drama',
    year: 2023,
    duration: 142,
    rating: 8.8,
    featured: true,
    language: 'Español'
  },
  {
    id: '7',
    title: 'Aventura Extrema',
    description: 'Un grupo de exploradores descubre un mundo perdido lleno de peligros y tesoros. La aventura más grande de sus vidas comienza.',
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'aventura',
    year: 2024,
    duration: 135,
    rating: 8.0,
    featured: false,
    language: 'Español'
  },
  {
    id: '8',
    title: 'El Mundo Mágico',
    description: 'Una película animada que encantará a toda la familia. Un viaje fantástico donde los sueños se hacen realidad.',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'animacion',
    year: 2024,
    duration: 98,
    rating: 8.5,
    featured: false,
    language: 'Español'
  },
  {
    id: '9',
    title: 'Naturaleza Salvaje',
    description: 'Un documental impresionante que explora los ecosistemas más remotos del planeta. Naturaleza en su estado más puro.',
    thumbnail: 'https://images.unsplash.com/photo-1474511320723-9a56873571b7?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'documental',
    year: 2023,
    duration: 105,
    rating: 9.0,
    featured: false,
    language: 'Español'
  },
  {
    id: '10',
    title: 'Código Vengador',
    description: 'Acción sin límites. Un agente especial debe detener una conspiración mundial antes de que sea demasiado tarde.',
    thumbnail: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'accion',
    year: 2024,
    duration: 130,
    rating: 8.3,
    featured: false,
    language: 'Español'
  },
  {
    id: '11',
    title: 'Noche de Pesadilla',
    description: 'El terror te acecha en cada esquina. Una noche que parece infinita para quienes se atreven a entrar en la mansión abandonada.',
    thumbnail: 'https://images.unsplash.com/photo-1509248961895-b4f8cb459a36?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'terror',
    year: 2024,
    duration: 108,
    rating: 7.8,
    featured: false,
    language: 'Español'
  },
  {
    id: '12',
    title: 'Destino Final',
    description: 'Un drama conmovedor sobre segundas oportunidades. A veces el destino nos da una nueva chance para hacer las cosas bien.',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: 'drama',
    year: 2023,
    duration: 128,
    rating: 8.4,
    featured: false,
    language: 'Español'
  }
]
